# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
  # require 'ib'
rescue LoadError
end

require 'rubygems'
require 'motion-dtrace'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'goldilocks'
end
